Create calculator template
tacettinkustu/microverse-math-magicians pull request #2
Opened 2021-08-11 18:17 UTC by tacettinkustu

2021-08-11 21:15 UTC, mricanho requested changes
Hi @tacettinkustu, 

Good job so far! Your Gitflow, commit messages and style are corrects!🔥🔥

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] Fix your README file and follow the tempĺate from microverse, remember that this is a good practice.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![believe in change](https://user-images.githubusercontent.com/60631456/129104412-421bb810-4669-4423-80d1-2f7af8572e0d.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 21:15 UTC, mricanho commented on src/App.js
> +  return <Calculator />;
- [ ] This component should be class-based. e.g.` class App extends Component {}`

2021-08-11 21:15 UTC, mricanho commented on src/components/Calculator.js
> +};
- [ ] This component should be class-based. e.g.

![imagen](https://user-images.githubusercontent.com/60631456/129103540-b385cd28-4fda-47af-9ca2-e0ed5e7737f4.png)

2021-08-11 22:06 UTC, tacettinkustu commented
> Hi @tacettinkustu,
> 
> Good job so far! Your Gitflow, commit messages and style are corrects!🔥🔥
> 
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * [x]  Fix your README file and follow the tempĺate from microverse, remember that this is a good practice.
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> ![believe in change](https://user-images.githubusercontent.com/60631456/129104412-421bb810-4669-4423-80d1-2f7af8572e0d.gif)
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

README file will be created later according to project phases.

2021-08-12 03:47 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @tacettinkustu 🔥 

You worked hard in all the instructions that I previously give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 06:22 UTC, merged